name: run tests
on: [push, workflow_dispatch]
jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download godot
        run: |
          wget https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_linux.x86_64.zip
          unzip Godot_v4.2.2-stable_linux.x86_64.zip
          mv Godot_v4.2.2-stable_linux.x86_64 godot
      - name: Run tests
        run: ./godot --headless -d -s --path . addons/gut/gut_cmdln.gd -gdir=res://test/unit -gexit
