name: run tests
on: [push, workflow_dispatch]
jobs:
  run_tests:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download godot
        run: |
          Invoke-WebRequest https://github.com/godotengine/godot/releases/download/4.2.2-stable/Godot_v4.2.2-stable_win64.exe.zip -OutFile Godot_v4.2.2-stable_win64.exe.zip
          unzip Godot_v4.2.2-stable_win64.exe.zip
          mv Godot_v4.2.2-stable_win64.exe godot.exe
      - name: Run tests
        run: ./godot --headless -d -s --path . addons/gut/gut_cmdln.gd -gdir=res://test/unit -gexit
